### ISSUE TITLE
Phone Number?

### ISSUE THREAD

**Issue by hollenberry** [brencis7/TshirtTime#1]
Hey @brencis7 ! 

One of the required fields in case shipping goes wrong is the phone number. If you want to pass that along, I put this order in today!

**Comment by brencis7** [comment]
Phone# 864-554-8529
The MAC is our internal mailing system, will help once it gets here. If you can't put it in a notes section don't worry about. 
Thanks again!

**Comment by hollenberry** [comment]
Order placed!

**Comment by brencis7** [comment]
Hey just wanted your thoughts really quick. Did some research and have had calls with several GitHub reps in the past and I really think the culture at the company is pulling me. Open, inclusive, not afraid to lead, while letting team members be themselves allowing a culture of innovation/ creativity... Very inspiring and I could see it thru the passion that you and @hectorsector in training and out. 

Sign me up for that! I will be applying to this [position](https://boards.greenhouse.io/github/jobs/807233#.WdJp32tSyT0) as it mirrors my current responsibilities and new ones that have always been interest of mine. 

Any tips or anything would be great, thanks again :v:

**Comment by hollenberry** [comment]
@brencis7 That's super exciting to hear! 

The only tip I have from my own interview process is that you should prepare for the process to take an extended period of time. I'd get that application started as soon as possible. Every interaction I had was incredibly quality during the process, and I was kept up to date by the recruiter, but there was some amount of time between rounds that caused me to sweat. 

🤞 !!

PS: Remember that this repo _is_ public. I'd recommend deleting these messages if you're concerned about that.

**Comment by brencis7** [comment]
:ok_hand:
